### ISSUE TITLE
Pull followed directly by push should work out of box

### ISSUE THREAD

**Issue by iNecas** [maria/foregit#14]
What I tried was pointing the repo path to some existing directory. In order to make it working, I needed additionally to:
1. create the directory
2. create the git repository
3. create origin remote because it expected it to be there

Would be nice, if I didn't have to do neither of these steps, foregit doing 1 and 2 for me, and for the 3. having there a remote might not be required at all

**Comment by maria** [comment]
I started implementing it here https://github.com/marianitadn/foregit/pull/16, like this:
- has local repo for given repo_path in settings?
  - yes: open repo
  - no -> has remote enabled?
    - yes -> has a git_remote defined in settings?
      - yes: clone repo in repo_path from git_remote
      - no: init local repo, compute remote address, add remote to local repo, commit, push to remote
    - no: init local repo

**Comment by maria** [comment]
All it's done expect `create origin remote` - because it would be a bit tricky in my opinion. It would mean that the user has to define the remote address, otherwise it would imply to many variables to create one, and it's easier for the user to create a repository and just add the link. 
We will do git pushes only if a remote is defined.

**Comment by iNecas** [comment]
sounds good
